insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (1, 'Zeitgeist: Moving Forward', 'Ruby Wooddisse', 2007, '€31,23');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (2, 'Broken Flowers', 'Fae Hacquoil', 2004, '€3,63');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (3, 'The Confessions of Bernhard Goetz', 'Grethel Kauffman', 2007, '€29,07');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (4, 'English Patient, The', 'Ivan Allott', 2009, '€38,74');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (5, 'Follow the Bitch', 'Redd Jellis', 1995, '€29,97');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (6, 'Funeral, The (Ososhiki)', 'Clovis Geeson', 1997, '€37,67');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (7, 'Prefab People, The (Panelkapcsolat)', 'Wittie Readwin', 2007, '€1,48');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (8, 'Amateurs, The (Moguls, The)', 'Alfie Wehden', 2010, '€18,95');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (9, 'What a Girl Wants', 'Bobinette Devita', 1990, '€29,58');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (10, 'Adopted', 'Krishna Davidsson', 2006, '€12,75');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (11, 'President''s Lady, The', 'Ariel Chelsom', 1998, '€26,49');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (12, 'All the King''s Men', 'Katrina Cappleman', 2004, '€20,25');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (13, 'Summer Wars (Samâ wôzu)', 'Rozina Melbury', 2000, '€5,89');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (14, 'Hondo', 'Ailbert Geerits', 1995, '€21,73');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (15, 'Black Pond', 'Drud Neville', 1991, '€39,96');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (16, 'American Adobo', 'Valentia Kubanek', 1998, '€4,23');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (17, 'Alice', 'Kristal Canacott', 1973, '€7,07');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (18, 'I Married a Witch', 'Georgina Dimitriades', 1985, '€32,80');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (19, 'Twins', 'Leonid Featenby', 1996, '€10,43');
insert into books (BookId, BookName, BookAuthor, YearOfPub, Price) values (20, 'Meeting Evil', 'Marcie Carrigan', 2005, '€8,20');
