insert into store (StoreId, StoreName, StoreAddress) values (1, 'Jacobi-Keebler', '244 Little Fleur Hill');
insert into store (StoreId, StoreName, StoreAddress) values (2, 'Effertz and Sons', '11828 Sage Lane');
insert into store (StoreId, StoreName, StoreAddress) values (3, 'Durgan LLC', '03 Northland Avenue');
insert into store (StoreId, StoreName, StoreAddress) values (4, 'Friesen-Parisian', '628 Redwing Drive');
insert into store (StoreId, StoreName, StoreAddress) values (5, 'Hauck-Little', '2 Sachtjen Point');
insert into store (StoreId, StoreName, StoreAddress) values (6, 'Kunde, Mohr and Ritchie', '7 Northview Avenue');
insert into store (StoreId, StoreName, StoreAddress) values (7, 'Oberbrunner, Jakubowski and Yundt', '06616 Parkside Avenue');
insert into store (StoreId, StoreName, StoreAddress) values (8, 'Hammes, Turner and Waelchi', '2 Birchwood Pass');
insert into store (StoreId, StoreName, StoreAddress) values (9, 'Turcotte, McCullough and Hessel', '82500 Sachs Lane');
insert into store (StoreId, StoreName, StoreAddress) values (10, 'Hilll, Kassulke and Stehr', '934 Bay Point');
insert into store (StoreId, StoreName, StoreAddress) values (11, 'Oberbrunner-Herzog', '95 Acker Plaza');
insert into store (StoreId, StoreName, StoreAddress) values (12, 'Baumbach, Krajcik and Mohr', '76084 La Follette Center');
insert into store (StoreId, StoreName, StoreAddress) values (13, 'Adams, Gutkowski and O''Hara', '5106 Vermont Parkway');
insert into store (StoreId, StoreName, StoreAddress) values (14, 'Corwin and Sons', '770 West Avenue');
insert into store (StoreId, StoreName, StoreAddress) values (15, 'Oberbrunner, Feil and O''Connell', '673 Gale Drive');
insert into store (StoreId, StoreName, StoreAddress) values (16, 'Spinka and Sons', '15689 Coleman Center');
insert into store (StoreId, StoreName, StoreAddress) values (17, 'Cremin Inc', '70090 Kedzie Court');
insert into store (StoreId, StoreName, StoreAddress) values (18, 'Schulist Group', '2 Kinsman Terrace');
insert into store (StoreId, StoreName, StoreAddress) values (19, 'Zboncak, Veum and Jacobson', '82610 Thackeray Plaza');
insert into store (StoreId, StoreName, StoreAddress) values (20, 'Cormier-Schaefer', '3894 Corry Center');
